### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ranjithshegde** [pierrep/ofxLibFreenect2#4]
Greetings

Thank you for your wonderful work. This seems like it really bridges the functionality gap bw

I see that in your example code you have commented out getDistanceAt class. Do you have any plans on reimplimenting this? If so I would be willing to help in any way I can. I am not too good at cpp but I can do testing and bugs for you

**Comment by pierrep** [comment]
Hi, I'll have a look at this when I get a chance. I disabled it because I didn't need it at the time and was trying to expedite development.

**Comment by ranjithshegde** [comment]
Thank you. Looking forward

**Comment by kdlydia** [comment]
> Hi, I'll have a look at this when I get a chance. I disabled it because I didn't need it at the time and was trying to expedite development.

have you had time to try? i’ve recently been struggling with this a lot so i'm very interested as well. would also like to help

**Comment by pierrep** [comment]
Not yet, I'm on holiday. Will have a look when I have some spare time

**Comment by pierrep** [comment]
OK I've added the getDistanceAt() class and added a point cloud to the example. I've also improved performance, there was an unnecessary colour conversion going on. I've also added the IR image.

I'm going to close this request, if you have any other problems just open a new issue.
